#!/bin/bash
set -euo pipefail

MYSQL_USER_NAME="${DB_USERNAME:-${MYSQL_USER:-qlpm}}"
MYSQL_USER_PASS="${DB_PASSWORD:-${MYSQL_PASSWORD:-qlpm}}"
MYSQL_APP_DB="${MYSQL_DATABASE:-${DB_NAME:-qlpm}}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-SQL
  CREATE DATABASE IF NOT EXISTS \`${MYSQL_APP_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE USER IF NOT EXISTS '${MYSQL_USER_NAME}'@'%' IDENTIFIED BY '${MYSQL_USER_PASS}';
  GRANT ALL PRIVILEGES ON \`${MYSQL_APP_DB}\`.* TO '${MYSQL_USER_NAME}'@'%';
  FLUSH PRIVILEGES;
SQL
