#!/bin/bash
set -euo pipefail

MYSQL_USER_NAME="${DB_USERNAME:-${MYSQL_USER:-qlpm}}"
MYSQL_USER_PASS="${DB_PASSWORD:-${MYSQL_PASSWORD:-qlpm}}"
MYSQL_DEV_DB="${MYSQL_DATABASE:-qlpm_development}"
MYSQL_TEST_DB="${MYSQL_TEST_DATABASE:-qlpm_test}"
MYSQL_PROD_DB="${MYSQL_PROD_DATABASE:-qlpm_production}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-SQL
  CREATE DATABASE IF NOT EXISTS \`${MYSQL_DEV_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS \`${MYSQL_TEST_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE DATABASE IF NOT EXISTS \`${MYSQL_PROD_DB}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
  CREATE USER IF NOT EXISTS '${MYSQL_USER_NAME}'@'%' IDENTIFIED BY '${MYSQL_USER_PASS}';
  GRANT ALL PRIVILEGES ON \`${MYSQL_DEV_DB}\`.* TO '${MYSQL_USER_NAME}'@'%';
  GRANT ALL PRIVILEGES ON \`${MYSQL_TEST_DB}\`.* TO '${MYSQL_USER_NAME}'@'%';
  GRANT ALL PRIVILEGES ON \`${MYSQL_PROD_DB}\`.* TO '${MYSQL_USER_NAME}'@'%';
  FLUSH PRIVILEGES;
SQL
